import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="wrapper flex flex-col relative min-h-screen">
          <header id="header" className="header flex flex-col md:flex-row md:justify-between items-center container mx-auto py-2 flex-wrap max-w-5xl" role="banner">
            <Link
              className="logo-link pl-2 lg:pl-0"
              href="/"
              aria-label="Back to home">
              <Image
                className="h-24"
                src="/images/logo/westerncode-horizontal.svg"
                alt="Western Code"
                width={240}
                height={96}
                priority
              />
            </Link>

          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
